abbreviations = {
	# Operational
	'COQ': 'Change Of Quarters',
	'FIP': 'Fire Indcator Pannel',
	'DESC': 'Descrpition',
	'RHS': 'Right Hand Side',
	'LHS': 'Left Hand Side',
	'NTH': 'Notheren',
	'STH': 'Southern',
	'SE': 'South East',
	'S/E': 'South East',
	'N': 'North',
	'NE': 'North EAST',
	'N/E': 'North EAST',
	'S': 'South',
	'SW': 'South WEst',
	'S/W': 'South West',
	'W': 'WEST',
	'NW': 'North West',
	'N/W': 'North West',
	'SPKL': 'Sprinker',
	'VLV': 'Valve',
	# Road Use
	'ALWY': 'ALLEYWAY',
	'ARC': 'ARCADE',
	'AV': 'AVENUE',
	'AVE': 'AVENUE',
	'BASN': 'BASIN',
	'BCH': 'BEACH',
	'BDGE': 'BRIDGE',
	'BDWY': 'BROADWAY',
	'BEND': 'BEND',
	'BLK': 'BLOCK',
	'BVD': 'BOULEVARD',
	'BYPA': 'BYPASS',
	'BYWY': 'BYWAY',
	'CAUS': 'CAUSEWAY',
	'CCT': 'CIRCUIT',
	'CDS': 'CUL-DE-SAC',
	'CH': 'CHASE',
	'CIR': 'CIRCLE',
	'CL': 'CLOSE',
	'CN': 'CENTRAL',
	'CNR': 'CORNER',
	'CNWY': 'CENTREWAY',
	'CON': 'CONCOURSE',
	'COVE': 'COVE',
	'COWY': 'CROSSWAY',
	'CR': 'CRESCENT',
	'CRD': 'CROSSROAD',
	'CRES': 'CRESCENT',
	'CRSG': 'CROSSING',
	'CRSS': 'CROSS',
	'CRST': 'CREST',
	'CT': '	COURT',
	'CTR': 'CENTRE',
	'CTYD': 'COURTYARD',
	'DEVN': 'DEVIATION',
	'DIP': 'DIP',
	'DR': 'DRIVE',
	'DRWY': 'DRIVEWAY',
	'DSTR': 'DISTRIBUTOR',
	'EDGE': 'EDGE',
	'ELB': 'ELBOW',
	'END': 'END',
	'ENT': 'ENTRANCE',
	'ESP': 'ESPLANADE',
	'EST': 'ESTATE',
	'EX': 'EXTENSION',
	'EXP': 'EXPRESSWAY',
	'FAWY': 'FAIRWAY',
	'FIT': 'FIRETRAIL',
	'FLAT': 'FLAT',
	'FRNT': 'FRONT',
	'FRTG': 'FRONTAGE',
	'FSHR': 'FORESHORE',
	'FTRK': 'FIRE TRACK',
	'FWY': 'FREEWAY',
	'GAP': 'GAP',
	'GDN': 'GARDEN',
	'GDNS': 'GARDENS',
	'GLEN': 'GLEN',
	'GLY': 'GULLY',
	'GR': 'GROVE',
	'GRA': 'GRANGE',
	'GRN': 'GREEN',
	'GRND': 'GROUND',
	'GTE': 'GATE',
	'HILL': 'HILL',
	'HRD': 'HIGHROAD',
	'HTS': 'HEIGHTS',
	'HWY': 'HIGHWAY',
	'INTG': 'INTERCHANGE',
	'INTN': 'INTERSECTION',
	'JNC': 'JUNCTION',
	'KEY': 'KEY',
	'LANE': 'LANE',
	'LDG': 'LANDING',
	'LINK': 'LINK',
	'LKT': 'LOOKOUT',
	'LNWY': 'LANEWAY',
	'LOOP': 'LOOP',
	'LR': 'LOWER',
	'LT': 'LITTLE',
	'MEWS': 'MEWS',
	'MT': 'MOUNT',
	'MWY': 'MOTORWAY',
	'NOOK': 'NOOK',
	'OTLK': 'OUTLOOK',
	'PARK': 'PARK',
	'PDE': 'PARADE',
	'PHWY': 'PATHWAY',
	'PIAZ': 'PIAZZA',
	'PKLD': 'PARKLANDS',
	'PKT': 'POCKET',
	'PKWY': 'PARKWAY',
	'PL': 'PLACE',
	'PLAT': 'PLATEAU',
	'PLZA': 'PLAZA',
	'PNT': 'POINT',
	'PORT': 'PORT',
	'PROM': 'PROMENADE',
	'QDGL': 'QUADRANGLE',
	'QDRT': 'QUADRANT',
	'QUAD': 'QUAD',
	'QY': 'QUAY',
	'QYS': 'QUAYS',
	'RCH': 'REACH',
	'RD': 'ROAD',
	'RDGE': 'RIDGE',
	'RDS': 'ROADS',
	'RDSD': 'ROADSIDE',
	'RDWY': 'ROADWAY',
	'RES': 'RESERVE',
	'RGWY': 'RIDGEWAY',
	'RMBL': 'RAMBLE',
	'RND': 'ROUND',
	'RNDE': 'RONDE',
	'RNGE': 'RANGE',
	'ROWY': 'RIGHT OF WAY',
	'RSBL': 'ROSEBOWL',
	'RTE': 'ROUTE',
	'RTT': 'RETREAT',
	'RTY': 'ROTARY',
	'RUN': 'RUN',
	'RVR': 'RIVER',
	'RVRA': 'RIVIERA',
	'RVWY': 'RIVERWAY',
	'SBWY': 'SUBWAY',
	'SDNG': 'SIDING',
	'SHWY': 'STATE HIGHWAY',
	'SLPE': 'SLOPE',
	'SND': 'SOUND',
	'SQ': 'SQUARE',
	'ST': 'STREET',
	'STRA': 'STRAND',
	'STRP': 'STRIP',
	'SWY': 'SERVICE WAY',
	'TCE': 'TERRACE',
	'THOR': 'THOROUGHFARE',
	'TKWY': 'TRUNKWAY',
	'TLWY': 'TOLLWAY',
	'TRI': 'TRIANGLE',
	'TRK': 'TRACK',
	'TRL': 'TRAIL',
	'TRLR': 'TRAILER',
	'TURN': 'TURN',
	'TWRS': 'TOWERS',
	'UP': 'UPPER',
	'UPAS': 'UNDERPASS',
	'VALE': 'VALE',
	'VDCT': 'VIADUCT',
	'VLLS': 'VILLAS',
	'VSTA': 'VISTA',
	'WALK': 'WALK',
	'WAY': 'WAY',
	'WHRF': 'WHARF',
	'WKWY': 'WALKWAY',
	'WYND': 'WYND',
	'YARD': 'YARD',
}
